y = input("Введите список чисел, разделенных пробелом: ").split()
print("Введенный список:", y)
x = list(map(int, y))
print("Максимальное значение:", max(x))
print("Мминимальное значение:", min(x))
print('По условию деления:', *(x for x in y if not int(x) % 3 and int(x) % 5))